<?php

return [
    'categories' => 'kategori',
    'business_sectors' => 'sektor usaha',
    'community_sectors' => 'bidang komunitas',
    'workplans' => 'program kerja',
    'workplan_reports' => 'laporan pertanggung jawaban',
    'pollings' => 'polling',
    'polling_items' => 'item polling',
    'votes' => 'vote',
    'vote_items' => 'item vote',
    'aspirations' => 'aspirasi',
    'business' => 'bisnis',
    'communities' => 'komunitas',
    'professions' => 'profesi',
    'statistics' => 'statistik',
    'pagination.next' => 'next',
    'pagination.previous' => 'prev',
    'supervision_id' => 'Supervisi',
    'executor_id' => 'Pelaksana',
    'category_id' => 'Kategori',
    'title' => 'Judul',
    'description' => 'Deskripsi',
    'file_path' => 'File',
    'budget' => 'Anggaran',
];